stackabletech/stackable-cockpit

web/package.json
web/src/main.tsx
yarn.lock

```[tasklist]
```
```[tasklist]
```
```[tasklist]
```

Add solidjs devtools

---

Cargo.lock
rust/stackable-cockpitd/Cargo.toml
rust/stackable-cockpitd/src/main.rs
web/index.html

First off: I have no idea what I'm doing. Had to use `ss -ltn` to find out the port it's running on, so I though it might make sense to print it out on startup.
I hope the title `Stackable cockpit` fits well, happy to change it.
```[tasklist]
```
```[tasklist]
```
```[tasklist]
```

feat(cockpit): Add startup message and update website title

---

deploy/helm/stackable-cockpit/templates/deployment.yaml
deploy/helm/stackable-cockpit/templates/roles.yaml
deploy/helm/stackable-cockpit/templates/service.yaml
deploy/helm/stackable-cockpit/values.yaml

Tested using
`helm upgrade --install stackable-cockpit ./deploy/helm/stackable-cockpit --set service.type=LoadBalancer`
```[tasklist]
```
```[tasklist]
```
```[tasklist]
```

fix: Fix helm-chart to deploy working installation

---

docs/antora.yml
docs/modules/cockpit/pages/index.adoc
docs/modules/cockpit/pages/installation.adoc
docs/modules/cockpit/partials/nav.adoc

Fixes #72
This doesn't include building instructions, since they seem to be disappearing from our other operators. This is intentionally kept pretty minimal right now (for example: it's probably not really worth going into deep detail on authn before we have #68).
```[tasklist]
```
```[tasklist]
```
```[tasklist]
```

Add deployment docs

---

docs/modules/cockpit/partials/nav.adoc

This is handled by the docs repo when including it.
```[tasklist]
```
```[tasklist]
```
```[tasklist]
```

Remove index page from nav hierarchy

---

web/package.json
web/src/api/schema.d.ts
yarn.lock

This fixes the issue of different versions producing different variants, thus chaning the schema back and forth.
```[tasklist]
```
```[tasklist]
```
```[tasklist]
```

bump: openapi-typescript to 6.5.0

---

.github/workflows/release_stackablectl.yaml
web/src/api/schema.d.ts

```[tasklist]
```
```[tasklist]
```
```[tasklist]
```

fix: Release workflow tag pattern

---

Cargo.lock
rust/stackable-cockpit/src/platform/cluster/resource_request.rs
rust/stackablectl/Cargo.toml

```[tasklist]
```
```[tasklist]
```
```[tasklist]
```

feat: Improve insufficient CPU warning message

---

Cargo.lock
extra/man/stackablectl.1
rust/stackablectl/Cargo.toml

chore: Release stackablectl-1.0.0-rc2

---

docs/modules/stackablectl/pages/commands/demo.adoc
docs/modules/stackablectl/pages/commands/operator.adoc
docs/modules/stackablectl/pages/commands/release.adoc
docs/modules/stackablectl/pages/commands/stack.adoc
docs/modules/stackablectl/pages/commands/stacklet.adoc
docs/modules/stackablectl/pages/customization/add-demo.adoc
docs/modules/stackablectl/pages/customization/add-release.adoc
docs/modules/stackablectl/pages/customization/add-stack.adoc
docs/modules/stackablectl/pages/customization/index.adoc
docs/modules/stackablectl/pages/index.adoc
docs/modules/stackablectl/pages/installation.adoc
docs/modules/stackablectl/pages/quickstart.adoc

```[tasklist]
```
```[tasklist]
```
```[tasklist]
```

docs: Fix redirects

---

.github/workflows/pr_docs.yml

This PR adds a GitHub Action workflow which gets triggered when doc pages are changed.

ci: Add docs workflow

---

rust/stackablectl/src/constants.rs

Part of https://github.com/stackabletech/issues/issues/455

refactor: Update demo/stack remote URLs

---

.github/workflows/pr_cockpit-web.yml
.github/workflows/pr_cockpit.yml
.github/workflows/pr_docs.yml
.github/workflows/pr_stackablectl.yml

Fixed the path globs so that PR workflows will run when files under the paths change.
```[tasklist]
```
```[tasklist]
```
```[tasklist]
```

ci: fix path matching for pr pipelines

---

.github/workflows/pr_cockpit.yml
.github/workflows/pr_general.yml
.github/workflows/pr_stackablectl.yml
.github/workflows/release_stackablectl.yml
rust-toolchain.toml

This bumps the Rust version to 1.74.0

chore: Bump Rust version

---

Cargo.lock
extra/man/stackablectl.1
rust/stackablectl/Cargo.toml

chore: Release stackablectl-23.11.1

---

.github/workflows/pr_stackablectl.yml

Following on from #164, would this suffice for automatic checks?
```[tasklist]
```
```[tasklist]
```
```[tasklist]
```

ci: ensure shell completions were updated

---

.github/workflows/pr_stackablectl.yml

- ensure man pages are up to date
```[tasklist]
```
```[tasklist]
```
```[tasklist]
```

ci: ensure man page is up to date

---

Cargo.lock
docs/modules/stackablectl/pages/installation.adoc
extra/man/stackablectl.1
rust/stackablectl/CHANGELOG.md
rust/stackablectl/Cargo.toml

Part of https://github.com/stackabletech/issues/issues/488

chore: Release stackablectl-24.3.0

---

Cargo.lock
rust/stackablectl/Cargo.toml

chore: Fix stackablectl version

---

rust/stackable-cockpit/src/utils/k8s/client.rs
rust/stackablectl/CHANGELOG.md

Fixes https://github.com/stackabletech/stackable-cockpit/issues/293
```[tasklist]
```
```[tasklist]
```
```[tasklist]
```

fix(stackablectl): Re-run GVK discovery after resolution failure

---

rust/stackable-cockpit/src/xfer/mod.rs

Part of https://github.com/stackabletech/stackable-cockpit/issues/182
```[tasklist]
```
```[tasklist]
```
```[tasklist]
```

chore: Improve file not found error message

---

docs/modules/stackablectl/pages/installation.adoc

The delimiters of a deep nested block needs to be different than the outer block.
```[tasklist]
```
```[tasklist]
```
```[tasklist]
```

docs: fix nested block

---

Makefile

Part of https://github.com/stackabletech/infrastructure/issues/143, includes pushing to harbor, signing images and building multi-arch in Makefile.
```[tasklist]
```
```[tasklist]
```
```[tasklist]
```

ci: Update Makefile to include operator-templating changes

---

.github/workflows/pr_cockpit.yml
Makefile

Add missing cosign and syft installations.
```[tasklist]
```
```[tasklist]
```
```[tasklist]
```

ci: Add cosign and syft to the cockpit workflow

---

.github/workflows/pr_cockpit.yml
.github/workflows/pr_docs.yml
.github/workflows/pr_stackablectl.yml

Remove reviewdog steps from workflows, because the reviewdog workflow does not exist anymore.
```[tasklist]
```
```[tasklist]
```
```[tasklist]
```

ci: Remove reviewdog from workflows

---

docs/modules/stackablectl/pages/installation.adoc

Fixes https://github.com/stackabletech/stackable-cockpit/issues/342

docs: Fix installation command on macOS for stackablectl

---

docs/modules/stackablectl/pages/installation.adoc

Docs: update release version in commands
```[tasklist]
```
```[tasklist]
```
```[tasklist]
```

docs: update release version in commands

---

docs/modules/stackablectl/pages/installation.adoc

This updates links from 24.11.1 to 24.11.3.

docs: Update release links to 24.11.3

---

.github/pull_request_template.md

Update PR template to not use tasklist
```[tasklist]
```
```[tasklist]
```
```[tasklist]
```

chore: update PR template to not use tasklist
