deploy/helm/stackable-cockpit/templates/service.yaml
Followup to #80.
```[tasklist]
```
```[tasklist]
```
```[tasklist]
```
=> Use named targetPort for cockpitd service

extra/completions/_stackablectl, extra/completions/stackablectl.bash, extra/completions/stackablectl.fish, rust/stackable-cockpit/src/constants.rs, rust/stackable-cockpit/src/xfer/cache.rs, rust/stackable-cockpit/src/xfer/mod.rs, rust/stackablectl/src/cmds/cache.rs, rust/stackablectl/src/cmds/demo.rs, rust/stackablectl/src/cmds/release.rs, rust/stackablectl/src/cmds/stack.rs, rust/stackablectl/src/main.rs
This PR adds a cache auto-purge feature, which cleans up cached files which are outdated. This is run even if the operation doesn't need cached (or remote) files. This helps to keep the cache folder clean.
The PR also adds `--old / --outdated` to the `stackablectl cache clean` command to only clear cached files which are outdated. Before this change, all cached files (even files not considered outdated) were deleted.
=> feat: Add cache auto-purge and `--old` arg to cache clean command

.github/workflows/build.yml, Cargo.lock, Cargo.toml
Windows build is currently broken.
Release workflow can be added trivially later on
```[tasklist]
```
```[tasklist]
```
```[tasklist]
```
=> Build binaries for Linux and MacOS

Cargo.lock, Cargo.toml, deny.toml, rust/stackablectl/Cargo.toml, rust/stackablectl/src/cli/mod.rs, rust/stackablectl/src/constants.rs, web/src/api/schema.d.ts
This is a drop-in replacement. Using `directories` enables us to build `stackablectl` for Windows as `xdg` didn't support Windows.
=> refactor: Replace `xdg` with `directories`

Cargo.lock, Cargo.toml, extra/man/stackablectl.1, rust/stackablectl/Cargo.toml, web/src/api/schema.d.ts
```[tasklist]
```
```[tasklist]
```
```[tasklist]
```
=> Release stackablectl 1.0.0-rc1

deploy/helm/stackable-cockpit/templates/roles.yaml
Leftover of #91
Now also works when installing via helm
```[tasklist]
```
```[tasklist]
```
```[tasklist]
```
=> fix: Add missing permission in clusterrole

rust/stackable-cockpit/src/platform/demo/spec.rs, rust/stackable-cockpit/src/platform/stack/spec.rs, rust/stackablectl/src/cmds/demo.rs, rust/stackablectl/src/cmds/release.rs, rust/stackablectl/src/cmds/stack.rs
Discovered by @sbernauer, brought forward in Slack chat.
=> fix(ctl): Skip creating operator-namespace when passing `--skip-release` in stack/demo command

rust/stackablectl/src/cli/mod.rs, rust/stackablectl/src/cmds/cache.rs, rust/stackablectl/src/cmds/completions.rs, rust/stackablectl/src/cmds/demo.rs, rust/stackablectl/src/cmds/operator.rs, rust/stackablectl/src/cmds/release.rs, rust/stackablectl/src/cmds/stack.rs, rust/stackablectl/src/cmds/stacklets.rs, rust/stackablectl/src/main.rs
Fixes #112 
The `completions` subcommand required access to the internet in order to work. This is not needed at all. The shell completions can be generated without any internet access. Additionally, the `cache` subcommand also doesn't require internet access from now on. Currently, it can only inspect and delete cached files.
Issue #112 is fixed by **not** adding the Helm repos if not required. This PR additionally slightly restructures the CLI code.
=> fix: The `completions` subcommand now works without internet access

docs/modules/stackablectl/pages/index.adoc, docs/modules/stackablectl/pages/quickstart.adoc
=> fix(docs): Update invalid xrefs in stackablectl docs

Cargo.lock
Bumps the `reqwest` version and should fix #120
=> chore: Bump reqwest version

rust/stackable-cockpitd/src/handlers/ui.rs
Obsoletes #136, see https://github.com/stackabletech/stackable-cockpit/pull/136#discussion_r1381278672
```[tasklist]
```
```[tasklist]
```
```[tasklist]
```
=> Fix duplicate `content-type` headers being sent for assets

README.md
Super minor fix, noticed `cargo xtask gen-mam` and fixed it.
```[tasklist]
```
```[tasklist]
```
```[tasklist]
```
=> docs: fix gen-man typo

.github/workflows/pr_general.yml, docs/modules/stackablectl/pages/commands/demo.adoc, docs/modules/stackablectl/pages/commands/operator.adoc, docs/modules/stackablectl/pages/quickstart.adoc
The listener-operator is now one of the fundamental operators, along with the commons- and secret-operators, and should be mentioned accordingly everywhere.
stackablectl 1.0.0-rc3 does not output anymore the installed operators, so I removed them:
```
The release commons-operator was successfully installed.
The release hive-operator was successfully installed.
The release opa-operator was successfully installed.
The release secret-operator was successfully installed.
The release superset-operator was successfully installed.
The release trino-operator was successfully installed.
```
Apply the settings from operator-templating to `rust-cache` and `cargo udeps` (https://github.com/stackabletech/operator-templating/blob/bacdd9bf7c66f0246092a8db89082d3d1dbc0703/template/.github/workflows/build. …
=> docs: Add listener-operator where missing

rust/stackablectl/src/cli/mod.rs, rust/stackablectl/src/cmds/demo.rs, rust/stackablectl/src/cmds/operator.rs, rust/stackablectl/src/cmds/release.rs, rust/stackablectl/src/cmds/stack.rs, rust/stackablectl/src/cmds/stacklet.rs
Resolves #142 
- Rename old `plain` output option to `table`
- Ceate a new output option for `plain` which removes border characters and disables dynamic table arrangement.
- There is an issue where there are multiple newlines between rows
- There should be further discussion about what plain output should look like. This PR felt like a good-enough compromise between existing code and avoiding broken hyperlinks
- We might need to use `force_no_tty()` when the output is plain, but I will look at that in a future PR where I add output options for `cache list`.
```[tasklist]
```
```[tasklist] …
```
=> feat: allow plain output support

rust/stackable-cockpit/src/helm.rs, rust/stackable-cockpit/src/platform/operator/mod.rs, rust/stackable-cockpit/src/platform/release/spec.rs, rust/stackable-cockpit/src/platform/service.rs, rust/stackable-cockpit/src/platform/stack/spec.rs, rust/stackablectl/CHANGELOG.md, rust/stackablectl/src/cmds/release.rs
Fixes the release uninstall process by deleting installed operators correctly.
=> fix: Uninstall operators when removing release

Cargo.lock, docs/modules/stackablectl/pages/installation.adoc, extra/man/stackablectl.1, rust/stackablectl/CHANGELOG.md, rust/stackablectl/Cargo.toml
=> chore: Release stackablectl-23.11.3

rust/stackable-cockpit/src/engine/kind/mod.rs, rust/stackable-cockpit/src/engine/minikube/mod.rs, rust/stackablectl/CHANGELOG.md, rust/stackablectl/src/args/cluster.rs, rust/stackablectl/src/cmds/demo.rs, rust/stackablectl/src/cmds/operator.rs, rust/stackablectl/src/cmds/release.rs, rust/stackablectl/src/cmds/stack.rs
Fixes an error reported by @sbernauer on Slack.
The provided `--cluster-name` was not used when creating the local cluster either using `kind` or `minikube`.
=> fix: Use the provided cluster name when creating a local cluster

.github/pull_request_template.md, .github/workflows/pr_cockpit.yml, Makefile, default.nix
Split the `build` and `publish` make targets and CI steps so that fork PRs don't fail on publish (due to not having github secret access for registry login).
Similar changes made in operator-templating:
- https://github.com/stackabletech/operator-templating/pull/334
- https://github.com/stackabletech/operator-templating/pull/336
=> ci: Fork awareness

Cargo.lock, docs/modules/stackablectl/pages/installation.adoc, extra/man/stackablectl.1, rust/stackablectl/CHANGELOG.md, rust/stackablectl/Cargo.toml
Includes the experimental `debug` command.
=> chore: Release stackablectl-24.3.1

.github/actionlint.yaml, .github/workflows/pr_general.yml, .github/workflows/pr_stackablectl.yml, .github/workflows/release_stackablectl.yml
Part of https://github.com/stackabletech/stackable-cockpit/issues/200
```[tasklist]
```
```[tasklist]
```
```[tasklist]
```
=> feat: Build aarch64 binary for Linux

Cargo.lock, Cargo.toml, rust/helm-sys/build.rs, rust/stackable-cockpit/src/platform/cluster/mod.rs, rust/stackable-cockpit/src/platform/cluster/resource_request.rs, rust/stackable-cockpitd/Cargo.toml, rust/stackable-cockpitd/src/main.rs, rust/stackable-cockpitd/src/middleware/authentication/mod.rs, rust/stackablectl/CHANGELOG.md, rust/stackablectl/src/cmds/debug.rs, web/src/api/schema.d.ts, yarn.lock
This bumps various Rust and Node dependencies. Currently `kube` cannot be bumped, because `stackable-operator` still uses `0.88.1`. This can be done once a new version of `stackable-operator` is releases.
Closes #231, closes #216. Other Node deps can be bumped as well, but might require adjustments.
=> chore: Bump Rust and Node deps

.github/pull_request_template.md, Cargo.lock, Makefile, docs/modules/stackablectl/pages/installation.adoc, extra/man/stackablectl.1, rust/stackablectl/CHANGELOG.md, rust/stackablectl/Cargo.toml
_(PR also includes a few pre-commit fixes)_
- Add pre-built binary for `aarch64-unknown-linux-gnu` ([#232]).
- Bump Rust dependencies ([#233]).
[#232]: https://github.com/stackabletech/stackable-cockpit/pull/232
[#233]: https://github.com/stackabletech/stackable-cockpit/pull/233
=> chore: Release stackablectl-24.3.2

docs/modules/cockpit/pages/installation.adoc, web/src/api/schema.d.ts
```[tasklist]
```
```[tasklist]
```
```[tasklist]
```
=> docs: Fix cockpit installation guide

.github/workflows/pr_cockpit-web.yml, .github/workflows/pr_reviewdog.yml, Cargo.lock, extra/man/stackablectl.1, rust/stackablectl/CHANGELOG.md, rust/stackablectl/Cargo.toml
Releases `stackablectl-24.3.3` to include the bumped dependencies from #238.
```[tasklist]
```
=> chore: Release stackablectl-24.3.3

Cargo.nix, default.nix, nix/sources.json, shell.nix, web/src/api/schema.d.ts
- Add nix-shell support
- Removed superfluous copy/paste stuff from default.nix, and rearranged it to work more like the operators.
- Update niv dependencies (`niv update`)
- Update nix cargo dependencies (`make regenerate-nix`)
- Update OpenAPI Typescript schema
> [!IMPORTANT]
> Should we add `niv update` to the `regenerate-nix` Make target?
> Also, should we add these nix dependency updates to the pre-commit hooks?
```[tasklist]
```
```[tasklist]
```
=> feat: Nix Shell support

rust/stackable-cockpit/src/platform/cluster/resource_request.rs, rust/stackable-cockpit/src/platform/credentials.rs, rust/stackable-cockpit/src/platform/demo/spec.rs, rust/stackable-cockpit/src/platform/manifests.rs, rust/stackable-cockpit/src/platform/namespace.rs, rust/stackable-cockpit/src/platform/service.rs, rust/stackable-cockpit/src/platform/stack/spec.rs, rust/stackable-cockpit/src/platform/stacklet/grafana.rs, rust/stackable-cockpit/src/platform/stacklet/minio.rs, rust/stackable-cockpit/src/platform/stacklet/mod.rs, rust/stackable-cockpit/src/platform/stacklet/opensearch.rs, rust/stackable-cockpit/src/platform/stacklet/prometheus.rs, rust/stackable-cockpitd/src/handlers/stacklets.rs, rust/stackablectl/CHANGELOG.md, rust/stackablectl/src/cmds/demo.rs, rust/stackablectl/src/cmds/operator.rs, rust/stackablectl/src/cmds/release.rs, rust/stackablectl/src/cmds/stack.rs, rust/stackablectl/src/cmds/stacklet.rs
Needs https://github.com/stackabletech/stackable-cockpit/pull/294 to properly work
Shows a significant speedup (e.g. when installing to IONOS) from 13s to 7.6s, the speedup is probably much higher on mobile networks (ask me after my next trip to Hamburg ^^)
```bash
➜  demos git:(observability-stack) ✗ time ~/stackable/stackable-cockpit/target/debug/stackablectl demo in end-to-end-security
WARN  RUNNING DISCOVERY
at rust/stackable-cockpit/src/utils/k8s/client.rs:80
Installed demo 'end-to-end-security'
Use "stackablectl operator installed" to display the installed operators.
Use "stackablectl stacklet list" to display the installed stacklets.
~/stackable/stackable-cockpit/target/debug/stackablectl demo in   2,72s user 0,55s system 43% cpu 7,430 total
➜  demos git:(observability-stack) ✗ …
```
=> chore: Avoid unnecessary k8s::Client creations

Cargo.lock, Cargo.nix, extra/man/stackablectl.1, rust/stackablectl/CHANGELOG.md, rust/stackablectl/Cargo.toml
```[tasklist]
```
```[tasklist]
```
```[tasklist]
```
=> chore: Release stackablectl-24.3.4

rust/helm-sys/build.rs, rust/stackable-cockpit/src/engine/kind/mod.rs, rust/stackable-cockpit/src/engine/minikube/mod.rs, rust/stackable-cockpit/src/helm.rs, rust/stackable-cockpit/src/platform/operator/mod.rs, rust/stackable-cockpit/src/utils/k8s/client.rs, rust/stackablectl/CHANGELOG.md, rust/xtask/src/docs.rs, web/src/api/schema.d.ts
The snafu report cleans up error messages by removing any content after a colon is encountered in the error message. This also messes up the output of structs when the Debug output is used. This was causing an issue when we failed to resolve a GVK.
=> fix: Remove colons from error messages

.gitattributes, .gitignore, .pre-commit-config.yaml, Cargo.nix, web/src/api/schema.d.ts
> [!IMPORTANT]
> We probably want to retag `24.3.5` once this is merged.
Without Cargo.nix being updated (via make regenerate-nix), the old version was still appearing in the new binary.
Additional improvements to speed up the pre-commit hook feedback loop.
=> fix: update Cargo.nix version and pre-commit hook improvements

rust/stackablectl/src/output/mod.rs
For now, let's remove the cleaning of error messages, because it hides too much detail. In the future, we should improve how these error messages are rendered in the terminal.
=> fix: Remove string cleaning in error report

.pre-commit-config.yaml, Cargo.lock, Cargo.nix, Makefile, docs/modules/stackablectl/pages/installation.adoc, extra/man/stackablectl.1, rust/stackablectl/CHANGELOG.md, rust/stackablectl/Cargo.toml
This release includes:
- Remove error message trimming in error report ([#303]).
[#303]: https://github.com/stackabletech/stackable-cockpit/pull/303
=> chore: Release stackablectl-24.3.6

Cargo.lock, Cargo.nix, docs/modules/stackablectl/pages/installation.adoc, extra/man/stackablectl.1, rust/stackablectl/CHANGELOG.md, rust/stackablectl/Cargo.toml
Releases stackablectl-24.7.0 which includes:
- helm-sys: Bump Go dependencies ([#307]).
- Bump Rust dependencies ([#307]).
- helm-sys: Double the helm timeout to 20m ([#306]).
[#306]: https://github.com/stackabletech/stackable-cockpit/pull/306
[#307]: https://github.com/stackabletech/stackable-cockpit/pull/307
=> chore: Release stackablectl-24.7.0

docs/modules/stackablectl/pages/installation.adoc
- Split install commands so that the copy button doesn't join them with `&&` (when only one needs to be run).
- Replace the `chmod` steps with the `install`. @fhennig I can revert that if you want to keep the instructions the same as they were.
- Windows: add a step to test the command
I won't fix the windows install instructions, eg:
- Do we assume CMD, PowerShell, or WSL2? (`cp` vs `copy`, `/usr/local/bin` vs `%USERPROFILE%\bin`)
- Adding `%USERPROFILE%\bin` to the user's `PATH` variable? And restarting the shell, or logging out and in again?
```[tasklist]
```
=> docs(stackablectl): simplify install steps

Cargo.lock, Cargo.nix, extra/man/stackablectl.1, rust/stackablectl/CHANGELOG.md, rust/stackablectl/Cargo.toml
This releases `stackablectl-24.7.1` which includes:
- helm-sys: Bump Go dependencies to fix critical vulnerability in `github.com/docker/docker`, See [CVE-2024-41110] ([#313]).
- nix: Fix broken build ([#311], [#314]).
[#311]: https://github.com/stackabletech/stackable-cockpit/pull/311
[#313]: https://github.com/stackabletech/stackable-cockpit/pull/313
[#314]: https://github.com/stackabletech/stackable-cockpit/pull/314
[CVE-2024-41110]: https://github.com/advisories/GHSA-v23v-6jw2-98fq
=> chore: Release stackblectl-24.7.1

.github/workflows/pr_pre-commit.yml, .pre-commit-config.yaml
Part of https://github.com/stackabletech/issues/issues/637
This fixes two things:
- Install the hadolint binary to be able to run the pre-commit hook
- Set the default language version of `node` to `system`. This fixes issues on NixOS systems.
=> fix(ci): Install hadolint in pre-commit workflow

.github/workflows/pr_cockpit.yml, docker/Dockerfile
Part of https://github.com/stackabletech/infrastructure/issues/143
```[tasklist]
```
```[tasklist]
```
```[tasklist]
```
=> ci: Add multiarch to cockpit workflow

.github/workflows/pr_pre-commit.yml, .pre-commit-config.yaml, Cargo.lock, Cargo.nix, extra/man/stackablectl.1, rust/stackablectl/CHANGELOG.md, rust/stackablectl/Cargo.toml
Part of https://github.com/stackabletech/issues/issues/647.
It should be noted that the release date is 2024-11-18 (next Monday at the time of writing) and it is required to push a tag after merging this PR into main.
---
This release includes:
- Bump Rust dependencies to fix critical vulnerability in `quinn-proto`, see [CVE-2024-45311] ([#318]).
- Bump Rust toolchain version to 1.80.1 ([#318]).
[#318]: https://github.com/stackabletech/stackable-cockpit/pull/318
[CVE-2024-45311]: https://github.com/advisories/GHSA-vr26-jcq5-fjj8
=> chore: Release stackablectl-24.11.0

.pre-commit-config.yaml, Cargo.lock, Cargo.nix, Cargo.toml, docs/modules/stackablectl/partials/commands/completions.adoc, extra/completions/_stackablectl, extra/completions/stackablectl.bash, extra/completions/stackablectl.elv, extra/completions/stackablectl.fish, extra/completions/stackablectl.nu, rust/stackablectl/CHANGELOG.md, rust/stackablectl/Cargo.toml, rust/stackablectl/src/cmds/completions.rs, rust/xtask/Cargo.toml, rust/xtask/src/completions.rs, rust/xtask/src/main.rs
- Nushell completions.
_Uses the [clap_complete_nushell] crate, as linked by the already used [clap_complete] crate._
- Elvish completions.
_Already included in [clap_complete], so why not?_ 
- Update xtasks to generate the new shell completions.
- New xtask command to run all xtasks (useful for local development).
- Disable shellcheck on generated completions.
[clap_complete_nushell]: https://crates.io/crates/clap_complete_nushell
[clap_complete]: https://crates.io/crates/clap_complete
=> feat: Add shell completions for Nushell and Elvish

Cargo.lock, Cargo.nix, extra/man/stackablectl.1, rust/stackablectl/CHANGELOG.md, rust/stackablectl/Cargo.toml
This release includes:
- Add shell completions for Nushell and Elvish ([#337]).
- SOCKS5 and HTTP proxy support ([#328]).
- Sort operator versions by semver version instead of alphabetically ([#336]).
[#328]: https://github.com/stackabletech/stackable-cockpit/pull/328
[#336]: https://github.com/stackabletech/stackable-cockpit/pull/336
[#337]: https://github.com/stackabletech/stackable-cockpit/pull/337
=> chore: Release stackablectl-24.11.1

.github/workflows/pr_pre-commit.yml
> [!CAUTION]
> This can only be merged when a tag was added in https://github.com/stackabletech/actions
This now installs Nix via the run-pre-commit action instead.
=> ci: Update run-pre-commit action

Cargo.lock, Cargo.nix, extra/man/stackablectl.1, rust/stackablectl/CHANGELOG.md, rust/stackablectl/Cargo.toml
This releases `stackablectl-24.11.2` which includes:
- Add new argument `--release` that allows installing a specific version of a demo or stack ([#340]).
- Remove argument `--offline` that was not implemented yet ([#340]).
[#340]: https://github.com/stackabletech/stackable-cockpit/pull/340
=> chore: Release stackablectl-24.11.2

docs/modules/stackablectl/pages/installation.adoc
This PR adds instructions for Nushell and Elvish completions (added in #337). It additionally simplifies the installation instructions.
**Preview:**
=> docs: Add new completions, simplify install instructions

.github/actionlint.yaml, .github/workflows/pr_stackablectl.yml, .github/workflows/release_stackablectl.yml, .pre-commit-config.yaml
This is our last repository still using BuildJet.
This PR tries to move to the new GitHub runners but we can also move to Ubicloud if needed
```[tasklist]
```
=> Move from BuildJet to GitHub ARM runners

Cargo.lock, Cargo.nix, extra/man/stackablectl.1, rust/stackablectl/CHANGELOG.md, rust/stackablectl/Cargo.toml
This PR releases stackablectl-24.11.3 which includes:
- Add new argument `--chart-source` so that operator charts can be pulled either from an OCI registry (the default) or from a index.yaml-based repository ([#344]).
[#344]: https://github.com/stackabletech/stackable-cockpit/pull/344
=> chore: Release stackablectl-24.11.3

Tiltfile, default.nix, deploy/helm/stackable-cockpit/values.yaml, docker/Dockerfile
Part of https://github.com/stackabletech/infrastructure/issues/142
Updates registry references to oci
```[tasklist]
```
```[tasklist]
```
```[tasklist]
```
=> chore: update to oci references

Cargo.lock, Cargo.nix, Cargo.toml, extra/man/stackablectl.1, rust/stackablectl/CHANGELOG.md, rust/stackablectl/Cargo.toml
Use `rustls-native-certs` so that `stackablectl` can be used in environments with internal PKI.
This is needed in the following cases:
- Internal mirrors of helm charts or stacks/demos signed by an internal CA.
- Firewalls that intercept HTTPS traffic.
=> fix: Use native CA certificates

rust/stackable-cockpit/src/platform/stacklet/minio.rs, rust/stackablectl/CHANGELOG.md
Fixes #363
Due to the minio charts being pre-rendered (until they can support TLS certs mounted directly on pods instead of via a Secret mount), the labels have slightly changed.
Therefore, stackable-cockpit needs to lookup a common label.
> [!TIP]
> Ideally we should have a new label that is applied to both `plainYaml` and `helmChart`, eg: `stackable.tech/stacklet: "true"` - but that is a little difficult without intercepting Helm Chart yamls.
24.11.1 demo:
```
┌──────────┬───────────────┬───────────┬─────────────────────────────────┬────────────────────────────────────────────┐
│ PRODUCT  ┆ NAME          ┆ NAMESPACE ┆ ENDPOINTS                       ┆ CONDITIONS                                 │
╞══════════╪═══════════════╪═══════════╪═════════════════════════════════╪═══════════════════ …
```
=> fix(stackable-cockpit/stacklet): Use heritage label for looking up minio

rust/helm-sys/src/lib.rs, rust/stackable-cockpit/src/engine/docker/mod.rs, rust/stackable-cockpit/src/engine/kind/mod.rs, rust/stackable-cockpit/src/engine/minikube/mod.rs, rust/stackable-cockpit/src/helm.rs, rust/stackable-cockpit/src/oci.rs, rust/stackable-cockpit/src/platform/demo/spec.rs, rust/stackable-cockpit/src/platform/manifests.rs, rust/stackable-cockpit/src/platform/operator/mod.rs, rust/stackable-cockpit/src/platform/release/spec.rs, rust/stackable-cockpit/src/platform/stack/spec.rs, rust/stackable-cockpit/src/utils/chartsource.rs, rust/stackable-cockpit/src/utils/check.rs, rust/stackablectl/CHANGELOG.md, rust/stackablectl/src/cli/mod.rs, rust/stackablectl/src/cmds/demo.rs, rust/stackablectl/src/cmds/operator.rs, rust/stackablectl/src/cmds/release.rs, rust/stackablectl/src/cmds/stack.rs, rust/stackablectl/src/cmds/stacklet.rs
This PR cleans up instrumented functions and tracing events.
```shell
stackablectl -l trace operator list # version 24.11.3
```
```shell
cargo run -p stackablectl -- -l trace operator list
```
=> chore(instrumentation): Reduce noise from instrumented functions

Makefile
Part of https://github.com/stackabletech/infrastructure/issues/142
This PR contains changes to the Makefile analogue to https://github.com/stackabletech/operator-templating/pull/502
```[tasklist]
```
```[tasklist]
```
```[tasklist]
```
=> ci: Update Makefile to include operator-templating changes

Cargo.lock, Cargo.nix, extra/man/stackablectl.1, rust/stackablectl/CHANGELOG.md, rust/stackablectl/Cargo.toml
This releases stackablectl **1.0.0**.
This is the **first** version released with the new versioning in place. Previously, the tool used the same versioning as our SDP releases, which lead to confusions, especially around patch-level releases. This is why we decided to use an independent versioning mechanism going forward.
- Pass the stack/demo namespace as a templating variable `NAMESPACE` to manifests.
This should unblock demos to run in all namespaces, as they can template the namespace e.g. for the FQDN of services ([#355]).
- Add progress reporting ([#376]).
- Include SparkConnectServer in the `stacklet list` output ([#380]).
- Add release upgrade functionality to `stackablectl release` command through `upgrade` subcommand ([#379]).
- Renamed `--product-namespace` argument to …
=> chore: Release stackablectl 1.0.0

.github/workflows/pr_stackablectl.yml, .github/workflows/release_stackablectl.yml
Part of #382.
During the release workflow, a job was cancelled because it used an outdated Ubuntu runner (20.04). All Ubuntu runners now use 24.04 instead.
=> ci: Bump Ubuntu runners

rust/stackablectl/src/cmds/operator.rs
docs: Clarify docs for operator install command
=> docs: Clarify docs for operator install command

Cargo.lock, Cargo.nix, extra/man/stackablectl.1, rust/stackablectl/CHANGELOG.md, rust/stackablectl/Cargo.toml
This releases stackablectl **1.1.0**.
- Add OpenSearch to the list of supported products ([#400]).
- nix: Update nixpkgs and upgrade nodejs-18 to nodejs_20 ([#384]).
- nix: Default to release build ([#388]).
- Switch to idempotent Helm installations for demos and stacks ([#386]).
- Ignore failed re-application of Jobs due to immutability in demo and stack installations.
Display those manifests to the user, so they can decide if they need to delete and recreate it ([#386]).
[#384]: https://github.com/stackabletech/stackable-cockpit/pull/384
[#386]: https://github.com/stackabletech/stackable-cockpit/pull/386
[#388]: https://github.com/stackabletech/stackable-cockpit/pull/388
[#400]: https://github.com/stackabletech/stackable-cockpit/pull/400
=> chore: Release stackablectl 1.1.0

docs/modules/stackablectl/nav.adoc, docs/modules/stackablectl/pages/release-notes.adoc, docs/modules/stackablectl/partials/release-notes/release-1.0.0.adoc, docs/modules/stackablectl/partials/release-notes/release-1.1.0.adoc, docs/modules/stackablectl/partials/release-notes/releases-old.adoc
Part of https://github.com/stackabletech/documentation/pull/757
This adds separate release notes for `stackablectl`.
=> docs: Add release notes for stackablectl

docs/modules/stackablectl/pages/installation.adoc
Small documentation update to reflect the current stackablectl version in installation commands
=> docs: update the stackablectl installation command to use the latest release

docs/modules/stackablectl/pages/customization/add-stack.adoc
Part of https://github.com/stackabletech/issues/issues/749 Quickfix
This PR updates the docs to use the bitnamilegacy repository for bitnami images. All affected examples ran successfully.
=> chore: update docs to use bitnamilegacy
